# Generated by Django 3.2 on 2023-05-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Код подтверждения'),
        ),
    ]
